# Generated by Django 4.0 on 2022-01-26 13:51

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import leads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_organiser', models.BooleanField(default=True)),
                ('is_agent', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('user_role', models.CharField(choices=[('E', 'Executive'), ('TL', 'Team Lead'), ('AM', 'Assistant Manager'), ('M', 'Manager'), ('HOD', 'Head Of Department')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(choices=[('Telecalling', 'Telecalling'), ('Field', 'Field'), ('Digital', 'Digital'), ('Reference', 'Reference')], max_length=15)),
                ('Product', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Insuarance', 'Insuarance'), ('Personal Loan', 'Personal Loan'), ('Over Draft', 'Over Draft')], max_length=20)),
                ('First_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=10, null=True)),
                ('Call_Status', models.CharField(blank=True, choices=[('Ringing', 'Ringing'), ('Switched Off', 'Switched Off'), ('Connected and Interested', 'Connected and Interested'), ('Connected and Not Interested', 'Connected and Not Interested'), ('Hung Up', 'Hung Up')], max_length=30, null=True)),
                ('Bank_Name', models.CharField(blank=True, choices=[('HDFC', 'HDFC BANK'), ('Kotak', 'Kotak Bank'), ('SBI', 'SBI Bank'), ('Yes', 'Yes Bank'), ('CITI', 'CITI Bank'), ('TATA', 'Tata Capital')], max_length=20, null=True)),
                ('Application_Type', models.CharField(blank=True, choices=[('C2C', 'Card 2 Card'), ('Salary', 'Salaried'), ('ITR', 'ITR')], max_length=30, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=40, null=True)),
                ('Created_at', models.DateField(auto_now_add=True)),
                ('Last_Upated', models.DateField(auto_now=True)),
                ('converted_date', models.DateField(blank=True, null=True)),
                ('Updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update', to='leads.agent')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agent')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.category')),
            ],
        ),
        migrations.CreateModel(
            name='SaleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserType', to='leads.department')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Fater_Name', models.CharField(max_length=40, null=True)),
                ('Mother_Name', models.CharField(max_length=40, null=True)),
                ('Date_of_Birth', models.DateField(null=True)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('PAN_Number', models.CharField(max_length=10, null=True)),
                ('Company_Name', models.CharField(max_length=30, null=True)),
                ('Designation', models.CharField(max_length=20, null=True)),
                ('Office_Address', models.CharField(max_length=500, null=True)),
                ('Current_Residence_Address', models.CharField(max_length=500, null=True)),
                ('Permanent_Residence_Address', models.CharField(max_length=500, null=True)),
                ('Personal_Email', models.EmailField(max_length=254, null=True)),
                ('Alternate_Phone_Number', models.CharField(blank=True, max_length=10, null=True)),
                ('Official_Email', models.EmailField(max_length=254, null=True)),
                ('Bank_Name', models.CharField(max_length=20)),
                ('Remarks', models.CharField(blank=True, max_length=40)),
                ('Application_Number', models.CharField(blank=True, max_length=30, null=True)),
                ('Created_at', models.DateField(auto_now_add=True)),
                ('Last_Upated', models.DateField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('converted_date', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agent')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='leads.salecategory')),
                ('lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('oraganisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saleupdate', to='leads.agent')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='oraganisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField()),
                ('follow_up_time', models.TimeField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=leads.models.handle_upload_documents)),
                ('pan_card', models.FileField(blank=True, null=True, upload_to=leads.models.handle_upload_documents)),
                ('kyc_documents', models.FileField(blank=True, null=True, upload_to=leads.models.handle_upload_documents)),
                ('card_copy', models.ImageField(blank=True, null=True, upload_to=leads.models.handle_upload_documents)),
                ('card_statement', models.FileField(blank=True, null=True, upload_to=leads.models.handle_upload_documents)),
                ('company_id', models.ImageField(blank=True, null=True, upload_to=leads.models.handle_upload_documents)),
                ('salary_slips', models.FileField(blank=True, null=True, upload_to=leads.models.handle_upload_documents)),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to=leads.models.handle_upload_documents)),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.sale')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='oraganisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='leads.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.usertype'),
        ),
    ]
