# Generated by Django 4.0 on 2022-01-28 11:06

from django.db import migrations, models
import django.db.models.deletion
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_document_bank_statement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='card_copy',
        ),
        migrations.RemoveField(
            model_name='document',
            name='card_statement',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Application_Type',
        ),
        migrations.AddField(
            model_name='sale',
            name='Application_Type',
            field=models.CharField(blank=True, choices=[('C2C', 'Card 2 Card'), ('Salary', 'Salaried'), ('ITR', 'ITR')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to=leads.models.handle_upload_kyc),
        ),
        migrations.AlterField(
            model_name='document',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='leads.sale'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.document'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='kyc_document',
            field=models.FileField(blank=True, null=True, upload_to=leads.models.handle_upload_kyc),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='salary_slip',
            field=models.FileField(blank=True, null=True, upload_to=leads.models.handle_upload_kyc),
        ),
        migrations.CreateModel(
            name='C2CDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_copy', models.ImageField(blank=True, null=True, upload_to=leads.models.handle_upload_kyc)),
                ('card_statement', models.FileField(blank=True, null=True, upload_to=leads.models.handle_upload_kyc)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.document')),
            ],
        ),
    ]
