# Generated by Django 4.0 on 2022-01-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_remove_document_card_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='Last_Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
