# Generated by Django 4.0 on 2021-12-31 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_oraganisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='oraganisation',
        ),
    ]
