# Generated by Django 4.0 on 2021-12-31 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_remove_lead_oraganisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='oraganisation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
            preserve_default=False,
        ),
    ]
