# Generated by Django 4.0 on 2022-02-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_sale_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='profile_picture',
        ),
    ]
