# Generated by Django 4.0 on 2022-01-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_converted_date_lead_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='Follow_up',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Follow_up_Date_Time',
        ),
    ]
