# Generated by Django 4.0 on 2022-02-06 09:46

from django.db import migrations, models
import leads.models
import rizcrm.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, storage=rizcrm.storage_backends.PublicMediaStorage(), upload_to=leads.models.handle_upload_kyc),
        ),
        migrations.AlterField(
            model_name='c2cdocument',
            name='card_copy',
            field=models.ImageField(blank=True, null=True, storage=rizcrm.storage_backends.PublicMediaStorage(), upload_to=leads.models.handle_upload_kyc),
        ),
        migrations.AlterField(
            model_name='c2cdocument',
            name='card_statement',
            field=models.FileField(blank=True, null=True, storage=rizcrm.storage_backends.PublicMediaStorage(), upload_to=leads.models.handle_upload_kyc),
        ),
        migrations.AlterField(
            model_name='document',
            name='company_id',
            field=models.ImageField(blank=True, null=True, storage=rizcrm.storage_backends.PublicMediaStorage(), upload_to=leads.models.handle_upload_documents),
        ),
        migrations.AlterField(
            model_name='document',
            name='pan_card',
            field=models.FileField(blank=True, null=True, storage=rizcrm.storage_backends.PublicMediaStorage(), upload_to=leads.models.handle_upload_documents),
        ),
        migrations.AlterField(
            model_name='document',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=rizcrm.storage_backends.PublicMediaStorage(), upload_to=leads.models.handle_upload_documents),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='salary_slip',
            field=models.FileField(blank=True, null=True, storage=rizcrm.storage_backends.PublicMediaStorage(), upload_to=leads.models.handle_upload_kyc),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=rizcrm.storage_backends.PublicMediaStorage(), upload_to='profile_pictures/'),
        ),
    ]
