# Generated by Django 4.0 on 2022-01-02 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_user_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='leads.usertype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Executive', 'E'), ('Team Lead', 'TL'), ('Assistant Manager', 'AM'), ('Manager', 'M'), ('HOD', 'HOD')], max_length=20),
        ),
    ]
