# Generated by Django 4.0 on 2022-01-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Executive', 'E'), ('Team Lead', 'TL'), ('Assistant Manager', 'AM'), ('Manager', 'M'), ('HOD', 'HOD')], max_length=20, null=True),
        ),
    ]
