# Generated by Django 4.0 on 2022-01-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
