# Generated by Django 4.0 on 2022-01-02 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_alter_usertype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('Executive', 'E'), ('Team Lead', 'TL'), ('Assistant Manager', 'AM'), ('Manager', 'M'), ('HOD', 'HOD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.usertype'),
        ),
    ]
