# Generated by Django 4.0 on 2022-01-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_alter_department_name_alter_user_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('E', 'Executive'), ('TL', 'Team Lead'), ('AM', 'Assistant Manager'), ('M', 'Manager'), ('HOD', 'Head Of Department')], max_length=20, null=True),
        ),
    ]
