# Generated by Django 4.0 on 2022-01-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_alter_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='follow_up_date',
            field=models.DateTimeField(null=True),
        ),
    ]
