# Generated by Django 4.0 on 2022-01-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_followup_follow_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='follow_up_date',
            field=models.DateTimeField(),
        ),
    ]
