# Generated by Django 4.0 on 2022-01-04 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_alter_followup_follow_up_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='Alternate_Phone_Number',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Bank_Statement',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Card_Copy',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Card_Number',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Card_Statement',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Company_ID',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Company_Name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Current_Residence_Address',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Date_of_Birth',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Designation',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Fater_Name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='KYC_Documents',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Mother_Name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Office_Address',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Official_Email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='PAN_Card_Photo',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='PAN_Number',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Permanent_Residence_Address',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Personal_Email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Salary_Slips',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='profile_picture',
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Fater_Name', models.CharField(blank=True, max_length=40, null=True)),
                ('Mother_Name', models.CharField(blank=True, max_length=40, null=True)),
                ('Date_of_Birth', models.DateField(blank=True, null=True)),
                ('PAN_Number', models.CharField(blank=True, max_length=10, null=True)),
                ('Company_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Designation', models.CharField(blank=True, max_length=20, null=True)),
                ('Office_Address', models.CharField(blank=True, max_length=500, null=True)),
                ('Current_Residence_Address', models.CharField(blank=True, max_length=500, null=True)),
                ('Permanent_Residence_Address', models.CharField(blank=True, max_length=500, null=True)),
                ('Personal_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Alternate_Phone_Number', models.IntegerField(blank=True, null=True)),
                ('Official_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Bank_Name', models.CharField(blank=True, choices=[('HDFC', 'HDFC BANK'), ('Kotak', 'Kotak Bank'), ('SBI', 'SBI Bank'), ('Yes', 'Yes Bank'), ('CITI', 'CITI Bank'), ('TATA', 'Tata Capital')], max_length=20, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=40, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Last_Upated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('converted_date', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agent')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='leads.category')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('oraganisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m')),
                ('PAN_Card_Photo', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m')),
                ('KYC_Documents', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m')),
                ('Card_Number', models.BigIntegerField(blank=True, null=True)),
                ('Card_Copy', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m')),
                ('Card_Statement', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m')),
                ('Salary_Slips', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m')),
                ('Company_ID', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m')),
                ('Bank_Statement', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads.sale')),
            ],
        ),
    ]
