# Generated by Django 4.0 on 2022-01-04 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_remove_lead_alternate_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Phone_Number',
            field=models.CharField(default=9643257889, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='Alternate_Phone_Number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Bank_Name',
            field=models.CharField(choices=[('HDFC', 'HDFC BANK'), ('Kotak', 'Kotak Bank'), ('SBI', 'SBI Bank'), ('Yes', 'Yes Bank'), ('CITI', 'CITI Bank'), ('TATA', 'Tata Capital')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Company_Name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Current_Residence_Address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Date_of_Birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Designation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Fater_Name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='sale',
            name='First_Name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Last_Name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Mother_Name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Office_Address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Official_Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='sale',
            name='PAN_Number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Permanent_Residence_Address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Personal_Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Remarks',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='sale',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agent'),
        ),
    ]
