# Generated by Django 4.0 on 2022-01-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_sale_phone_number_alter_sale_alternate_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='Card_Number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Alternate_Phone_Number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
