# Generated by Django 4.0 on 2022-01-04 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_alter_documents_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='Bank_Name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Company_Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Current_Residence_Address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Date_of_Birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Designation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Fater_Name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Mother_Name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Office_Address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Official_Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='PAN_Number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Permanent_Residence_Address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Personal_Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
    ]
