# Generated by Django 4.0 on 2022-01-04 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_alter_sale_bank_name_alter_sale_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads.sale'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
    ]
