# Generated by Django 4.0 on 2022-01-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_alter_documents_sale_alter_sale_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='lead',
        ),
        migrations.AlterField(
            model_name='lead',
            name='Phone_Number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Phone_Number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
