# Generated by Django 4.0 on 2022-01-04 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_remove_sale_lead_alter_lead_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='lead',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
            preserve_default=False,
        ),
    ]
