# Generated by Django 4.0 on 2022-01-04 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_sale_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads.sale'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
    ]
