# Generated by Django 4.0 on 2022-01-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0032_alter_documents_sale_alter_sale_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='lead',
        ),
    ]
