# Generated by Django 4.0 on 2022-01-04 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_remove_sale_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
    ]
