# Generated by Django 4.0 on 2022-01-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0034_sale_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='Card_Number',
        ),
    ]
