# Generated by Django 4.0 on 2022-01-10 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0035_remove_documents_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='id',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='sale',
        ),
        migrations.AddField(
            model_name='documents',
            name='sale_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leads.sale'),
            preserve_default=False,
        ),
    ]
