# Generated by Django 4.0 on 2022-01-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0038_remove_lead_status_sale_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='file',
        ),
    ]
