# Generated by Django 4.0 on 2022-01-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0039_remove_followup_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='Status',
        ),
    ]
