# Generated by Django 4.0 on 2022-01-20 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0041_salecategory_remove_category_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='sale_ptr',
        ),
        migrations.AddField(
            model_name='documents',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.sale'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='leads.salecategory'),
        ),
    ]
