# Generated by Django 4.0 on 2022-01-20 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0041_salecategory_remove_category_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='leads.salecategory'),
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
