# Generated by Django 4.0 on 2022-01-20 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0042_remove_documents_sale_ptr_documents_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='sale',
        ),
    ]
