# Generated by Django 4.0 on 2022-01-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0042_alter_sale_category_delete_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='follow_up_date',
            field=models.DateField(),
        ),
    ]
