# Generated by Django 4.0 on 2022-01-20 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0043_remove_documents_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.sale'),
        ),
    ]
