# Generated by Django 4.0 on 2022-01-22 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0044_lead_updated_by_sale_application_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_copy', models.ImageField(blank=True, null=True, upload_to='Documents/')),
                ('card_statement', models.FileField(blank=True, null=True, upload_to='Documents/')),
                ('company_id', models.ImageField(blank=True, null=True, upload_to='Documents/')),
                ('salary_slips', models.FileField(blank=True, null=True, upload_to='Documents/')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.sale')),
            ],
        ),
    ]
