# Generated by Django 4.0 on 2022-01-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0045_documents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
    ]
