# Generated by Django 4.0 on 2022-01-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0046_rename_documents_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='kyc_document',
            field=models.FileField(blank=True, null=True, upload_to='Documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='Documents/'),
        ),
    ]
