# Generated by Django 4.0 on 2022-01-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0047_document_kyc_document_document_pan_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='Documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Documents/'),
        ),
    ]
