# Generated by Django 4.0 on 2022-01-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0048_document_bank_statement_document_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='follow_up_date',
            field=models.DateTimeField(),
        ),
    ]
