# Generated by Django 4.0 on 2022-01-23 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0049_alter_followup_follow_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='follow_up_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followup',
            name='follow_up_date',
            field=models.DateField(),
        ),
    ]
