# Generated by Django 4.0 on 2022-01-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0050_followup_follow_up_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='card_copy',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='card_statement',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='company_id',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='kyc_document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='salary_slips',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
