# Generated by Django 4.0 on 2022-01-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0051_alter_document_bank_statement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='kyc_document',
        ),
        migrations.AddField(
            model_name='document',
            name='kyc_documents',
            field=models.FileField(blank=True, null=True, upload_to='Documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='Documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='card_copy',
            field=models.ImageField(blank=True, null=True, upload_to='Documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='card_statement',
            field=models.FileField(blank=True, null=True, upload_to='Documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='company_id',
            field=models.ImageField(blank=True, null=True, upload_to='Documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='Documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='salary_slips',
            field=models.FileField(blank=True, null=True, upload_to='Documents/'),
        ),
    ]
