# Generated by Django 4.0 on 2022-01-24 18:06

from django.db import migrations, models
import django.utils.timezone
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0053_alter_document_bank_statement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to=leads.models.handle_upload_documents),
        ),
        migrations.AlterField(
            model_name='document',
            name='card_copy',
            field=models.ImageField(blank=True, null=True, upload_to=leads.models.handle_upload_documents),
        ),
        migrations.AlterField(
            model_name='document',
            name='card_statement',
            field=models.FileField(blank=True, null=True, upload_to=leads.models.handle_upload_documents),
        ),
        migrations.AlterField(
            model_name='document',
            name='company_id',
            field=models.ImageField(blank=True, null=True, upload_to=leads.models.handle_upload_documents),
        ),
        migrations.AlterField(
            model_name='document',
            name='kyc_documents',
            field=models.FileField(blank=True, null=True, upload_to=leads.models.handle_upload_documents),
        ),
        migrations.AlterField(
            model_name='document',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to=leads.models.handle_upload_documents),
        ),
        migrations.AlterField(
            model_name='document',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=leads.models.handle_upload_documents),
        ),
        migrations.AlterField(
            model_name='document',
            name='salary_slips',
            field=models.FileField(blank=True, null=True, upload_to=leads.models.handle_upload_documents),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Last_Upated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
