# Generated by Django 4.0 on 2022-01-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0054_alter_document_bank_statement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Last_Upated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='PAN_Number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Phone_Number',
            field=models.CharField(max_length=10),
        ),
    ]
