# Generated by Django 4.0 on 2022-01-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0055_alter_lead_created_at_alter_lead_last_upated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Last_Upated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Phone_Number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='converted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Last_Upated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='PAN_Number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='converted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
