# Generated by Django 4.0 on 2022-01-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0056_lead_email_alter_lead_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='PAN_Number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
