# Generated by Django 4.0 on 2022-01-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0057_remove_lead_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
