# Generated by Django 4.0 on 2022-01-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0057_alter_sale_pan_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='Email',
        ),
    ]
