# Generated by Django 4.0 on 2022-01-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0058_remove_lead_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='Created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Last_Upated',
            field=models.DateField(auto_now=True),
        ),
    ]
