# Generated by Django 4.0 on 2022-01-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0058_lead_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='Email',
        ),
    ]
